services:
  app:
    image: julionsc/saquepix
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=saquepix
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-data:
